---
- hosts: masters
  remote_user: k8suser
  become: yes
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Ensure NFS packages are installed
      apt:
        name:
          - nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create the NFS export directory
      file:
        path: /srv/nfs/shared
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs/shared *(rw,sync,no_subtree_check)"
        state: present

    - name: Export the NFS shares
      command: exportfs -ra

    - name: Enable and start the NFS service
      systemd:
        name: nfs-server
        enabled: yes
        state: started

    - name: Transfer a folder to the NFS share on the master node
      synchronize:
        src: "{{ lookup('env', 'HOME') }}/ansible_model/cluster/nfs-share"
        dest: /srv/nfs/shared/
        recursive: yes
        delete: no
        archive: yes
        rsync_opts:
          - "--no-perms"       
          - "--no-owner"       
          - "--no-group"       
          - "--omit-dir-times" 
          - "--no-times"       
      become: no